### PR TITLE
Update knowledge-work-tutorial.md

### PR DESCRIPTION
**Pull request by yudoufu**
The service already changed ACS URL to new one.
So we need to fix the document.

### CODE REVIEW

**Comment by Court72** [comment]
@jeevansd

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by yudoufu** [comment]
@jeevansd @Court72 Hi! Could you please review this? 😄

**Comment by Court72** [comment]
@dhivyagana (per @jeevansd's OOF message) can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge.

**Comment by Gicheha** [comment]
#sign-off

**Comment by Gicheha** [comment]
#please-close

**Comment by dhivyagana** [comment]
@Gicheha please re open this PR.

**Comment by Jak-MS** [comment]
@dhivyagana - reopened. please review. thanks!

**Review by dhivyagana — APPROVED** [review]
#sign-off

**Pull request merged**
