### PR TITLE
Update reference-connect-version-history.md

### PR DESCRIPTION
**Pull request by akhiraka**
The notation needs to be updated to the current correct supported version.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@billmath - 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Jak-MS** [comment]
#assign: @billmath

**Comment by Jak-MS** [comment]
hi @CelesteDG - temporarily assigning this to you... we aren't able to assign @billmath - likely due to repo restrictions

**Comment by CelesteDG** [comment]
Thank you, @Jak-MS 
Reassigned to @billmath

**Comment by billmath** [comment]
Fixed.

**Comment by billmath** [comment]
#please-close

**Pull request closed without merging**
