### PR TITLE
Update permissions-reference.md

### PR DESCRIPTION
**Pull request by VipulMSFT**
Corrected the list of tasks that the attack payload author can do. Relevant reference: https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-get-started?view=o365-worldwide#what-do-you-need-to-know-before-you-begin

### CODE REVIEW

**Comment by Court72** [comment]
@rolyon

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rolyon** [comment]
Hi @VipulMSFT
Thanks for your pull request. I still see this action listed in the portal and Graph API for the Attack Payload Author role. The documentation matches what I currently see.
Can you clarify why this action should be deleted?
thanks

**Comment by rolyon** [comment]
Hi @VipulMSFT 
I still see this action listed in the portal, so I'm going to close this pull request.
Let us know if you have any additional feedback.
thanks

**Comment by rolyon** [comment]
#please-close

**Pull request closed without merging**
