### PR TITLE
Added new section that calls out setting assignment required property setting to Yes from the dault No

### PR DESCRIPTION
**Pull request by steven-twingate**
This setting is No by default which allows any user that is part of Entra ID to be able to log into twingate even if they were not assigned to the enterprise application.

### CODE REVIEW

**Comment by steven-twingate** [comment]
@microsoft-github-policy-service agree [company="{Twingate}"]

**Comment by steven-twingate** [comment]
@microsoft-github-policy-service agree company="Twingate"

**Comment by steven-twingate** [comment]
Corrected Warnings.

**Comment by Court72** [comment]
@twimmers

Can you review the proposed changes? Note that the new images must be added to a **media** folder and the [validation warning](https://github.com/MicrosoftDocs/entra-docs/pull/168#issuecomment-1882046775) must be resolved before merging.

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by steven-twingate** [comment]
help with review?

**Comment by v-missam** [comment]
Hi @steven-twingate since we were facing issue approving this PR, so we have raised separate PR for your suggested changes. The tutorial should be updated in next 48hrs

**Comment by v-missam** [comment]
#please-close

**Pull request closed without merging**
