### PR TITLE
Palo Alto Networks GlobalProtect: Include additional information and wording improvements

### PR DESCRIPTION
**Pull request by matsimon**
Add Reply URL (Assertion Consumer Service URL) as documented by Palo Alto Networks, see:
[How to setup Azure SAML authentication with GlobalProtect](https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g0000008U48CAE)

Reword the section about the Metadata XML file since it contains quite a bit more than just the SAML signing certificate.
Reference a generic file name instead of metadata.xml (it isn't always named like that and may lead to user confusion).

Mention import IdP errors that may be caused by lack of privileges of the signed-in user or 31 character limit of the SAML profile name. 

Concerning the 31 character limit, see PAN customer support portal: 
[SAML IdP Metadata import fails with error message “Failed to parse IDP Metadata” due to Profile name having more than 31 characters](https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA14u000000wlFiCAI&lang=en_US%E2%80%A9)

The XML import error due to lack of privilege issue is based on personal experience. I don't know the exact permission required on PAN-OS, but I can confirm that it ended up working with superuser permissions.

### CODE REVIEW

**Comment by Court72** [comment]
@jeevansd

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by v-hgampala** [comment]
@matsimon, we're creating a separate PR for this in our repo for better content validation, you can expect the changes within 3-4 working days.
#please-close

**Comment by matsimon** [comment]
Hi, thanks for the update, I wanted to ping on this topic since the current documentation hasn't been updated since (last update was in late 2023).

**Comment by v-hgampala** [comment]
@matsimon, the article has updated as per your request, please let us know where isn't updated -https://learn.microsoft.com/en-us/entra/identity/saas-apps/palo-alto-networks-globalprotect-tutorial

**Pull request closed without merging**
