### PR TITLE
Update cisco-user-management-for-secure-access-provisioning-tutorial.md

### PR DESCRIPTION
**Pull request by kbhawkey**
Add mapping from originalUserPrincipleName to UserName to enable a Microsoft Entra guest user account.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@twimmers 
Can you review this PR? Sign-off or approve if you're okay with the changes.

NOTE: To sign off, add `#sign-off`to a comment."

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by kbhawkey** [comment]
This pull request adds information about mapping a guest Azure account to the UserName attribute in the Cisco User Management app.

**Comment by kbhawkey** [comment]
@microsoft-github-policy-service agree company=cisco

**Comment by v-missam** [comment]
Hi @kbhawkey do you work with Cisco team or are you a customer of Cisco team? Could you please drop an email to the alias <aaduserprovisioning@microsoft.com> with the tutorial change ask so that we can implement it soon on the tutorial

**Comment by v-missam** [comment]
#sign-off

**Comment by v-missam** [comment]
Closing this PR as we didn't any response from the user on our previous ask. 

#please-close

**Pull request closed without merging**
