### PR TITLE
Add a note about id_token validation in the EAM concept docs

### PR DESCRIPTION
**Pull request by damienbod**
Add a note to the validation section in the __Microsoft Entra multifactor authentication external method provider reference__

Weak validation can result in security problems.

### CODE REVIEW

**Comment by Court72** [comment]
@gregkmsft

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by gregkmsft — CHANGES_REQUESTED** [review]
Suggested change from ">It is very important to validate the id_token_hint value fully, including the signature. You must ensure that the identity token is from a known Microsoft Entra ID tenant. The claims from the JWT token must be used for the MFA validation processing."

to 

">It is important to validate the id_token_hint to ensure the id_token_hint is from a Microsoft tenant and represents your integration.  The id_token_hint should be fully validated, particularly the signature, issuer, audience as well as the other claim values. "

**Comment by damienbod** [comment]
@gregkmsft updated, thanks for the feedback

**Review by gregkmsft — APPROVED** [review]

**Comment by gregkmsft** [comment]
#sign-off

**Pull request merged**
