### PR TITLE
Update access-tokens.md

### PR DESCRIPTION
**Pull request by ruaden94**
There needs to be a special note in our public document that access tokens are issued by our sts service. So the Issuer of the access token will be https://sts.windows.net/aaaabbbb-0000-cccc-1111-dddd2222eeee/

### CODE REVIEW

**Comment by ruaden94** [comment]
There should be a special note section to call this out in the public document. As we have had cases on the Microsoft support side where developers are asking why the issuer is not https://login.microsoftonline.com/tenant id/   as stated in the public doc.  

This will help remove confusion from our public doc and explicitly state that access tokens are issued by the sts service - https://sts.windows.net/tenant id/

**Comment by Court72** [comment]
@cilwerner

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by cilwerner** [comment]
@ruaden94, that is true for v1.0 tokens. Check the tokens in [token formats](https://learn.microsoft.com/en-us/entra/identity-platform/access-tokens#token-formats) using [jwt.ms](https://jwt.ms/) and you'll see that the `iss` claim is `login.microsoftonline...` for v2.0 tokens and `sts...` for v1.0 tokens. We recommend to use v2.0 tokens.

**Comment by cilwerner** [comment]
#please-close

**Pull request closed without merging**
