### PR TITLE
Update prodpad-tutorial.md

### PR DESCRIPTION
**Pull request by SamsRunningWild**
Updates to the ProdPad configuration steps - these were out of date and misleading to users

### CODE REVIEW

**Comment by SamsRunningWild** [comment]
@microsoft-github-policy-service agree [company="createshift"]
@microsoft-github-policy-service agree
@microsoft-github-policy-service agree company="Microsoft"

**Comment by SamsRunningWild** [comment]
@microsoft-github-policy-service agree

**Comment by SamsRunningWild** [comment]
@microsoft-github-policy-service agree company="createshift"

**Comment by Court72** [comment]
@jeevansd

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Gicheha** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@Gicheha 
PRMerger will only accept sign off from the listed 'author'. However, if you are a Microsoft employee authorized to update this content, you can send a request to [techdocprs@microsoft.com](mailto:techdocprs@microsoft.com) for this PR to be merged.  Include your role, and an explanation of why the PR should be merged without approval from the listed author.

**Comment by Gicheha** [comment]
#please-close

**Pull request closed without merging**
