### PR TITLE
Update the table for authenticator passwordless

### PR DESCRIPTION
**Pull request by chiyao-ms**
Update the table for authenticator passwordless since it can be used as secondary authentication only when CBA is primary authentication.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@Justinha 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by chiyao-ms** [comment]
Hello @Justin ***@***.***>,
My name is Chi from Azure ID team of Japan.

We have a S500 customer waiting for this to be published.
It would be really appreciated if you could review this in priority.

Thank you.
-chiyao-

**Comment by Jak-MS** [comment]
nudge @Justinha - can you take a look? (the link needs to be fixed, but I can do that if you'd like... ) thanks!

**Review by Justinha — COMMENTED** [review]
I submitted a parallel PR at https://github.com/MicrosoftDocs/entra-docs-pr/pull/2146

**Pull request closed without merging**
