### PR TITLE
Update zola-tutorial.md

### PR DESCRIPTION
**Pull request by IQbrod**

### CODE REVIEW

**Comment by Court72** [comment]
@jeevansd

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by IQbrod** [comment]
@jeevansd can we get an approval on this so we can update our documentation ?
Regards

**Comment by IQbrod** [comment]
Guys, it's been two weeks for minor changes in a markdown file, can we get an approval by anybody else please ?
We would like to share the documentation with these changes to our clients.

Regards

@Court72 @jeevansd

**Comment by Court72** [comment]
@jeevansd, @CelesteDG 

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge.

**Comment by rosianahm** [comment]
@jeevansd I have reviewed the changes, and it is good to go. Please add your #signoff to merge this PR.

**Comment by IQbrod** [comment]
Guys ... 
Alt Text

We're almost at three weeks now.

@jeevansd @Court72 @rosianahm

**Comment by jeevansd** [comment]
Sorry guys for my late response. But providing my sign off here #sign-off

**Pull request merged**
