### PR TITLE
Update timetabling-solutions-tutorial.md

### PR DESCRIPTION
**Pull request by pgthomps**
Added missing steps

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@jeevansd

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by pgthomps** [comment]
#sign-off

**Comment by pgthomps** [comment]
When will this be updated?

**Comment by v-hgampala** [comment]
@pgthomps, thanks for the request!!
we're creating a separate PR for these changes in our repo for better content validation, the changes will publish within 1-2 working days and closing this request for now.
#please-close

**Pull request closed without merging**
