### PR TITLE
Fix issues in tutorial Vanilla Javascript SPA

### PR DESCRIPTION
**Pull request by igor-h**
Fix small issues found in the Content: [Tutorial - Handle authentication flows in a Vanilla JavaScript single-page app - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/tutorial-single-page-app-vanillajs-configure-authentication)

Related with:
https://github.com/MicrosoftDocs/entra-docs/issues/449

### CODE REVIEW

**Comment by igor-h** [comment]
@microsoft-github-policy-service agree company="Avolta"

**Comment by Jak-MS** [comment]
@OwenRichards1 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by igor-h** [comment]
Without my fix, when you run the application locally, you get 2 errors.

1. `loginRequest `doesn't exist.
2. `msalObj` **not inizialized**, and then the application crash.

@OwenRichards1

**Comment by igor-h** [comment]
Closing the PR as the issue was already resoled in the :main branch on MicrosoftDocs.  [MicrosoftDocs:main](https://github.com/MicrosoftDocs/entra-docs/tree/main)

**Pull request closed without merging**
