### PR TITLE
Update v2-oauth2-client-creds-grant-flow.md

### PR DESCRIPTION
**Pull request by vladik-vitre**
Fixed the Bash examples to match the HTTP examples

### CODE REVIEW

**Comment by Jak-MS** [comment]
@OwenRichards1 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by vladik-vitre** [comment]
Can someone approved or decline?

**Comment by Jak-MS** [comment]
nudge @OwenRichards1 - please review.

**Review by OwenRichards1 — APPROVED** [review]
LGTM - thanks!

**Comment by OwenRichards1** [comment]
#sign-off

**Pull request merged**
