### PR TITLE
Fix example with missing &

### PR DESCRIPTION
**Pull request by autosysops**
Fixes https://github.com/MicrosoftDocs/entra-docs/issues/259

### CODE REVIEW

**Comment by Court72** [comment]
@OwenRichards1

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by autosysops** [comment]
Any news on this PR?

**Review by OwenRichards1 — APPROVED** [review]
LGTM! Thanks for spotting this.

**Comment by Court72** [comment]
@OwenRichards1, @autosysops - This PR has developed a merged conflict that we're unable to resolve via the GitHub UI. Can you resolve the conflict?

**Comment by Court72** [comment]
@OwenRichards1 - I'll merge this PR based on your approval. If this article requires further changes, please open a separate pull request.

**Pull request merged**
