### PR TITLE
Add note that apps must be registered in a directory to identity platform updates reference

### PR DESCRIPTION
**Pull request by aricrowe57**

### CODE REVIEW

**Comment by aricrowe57** [comment]
Note: update in progress, should be done by EOD today

**Comment by Jak-MS** [comment]
@rwike77 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by aricrowe57** [comment]
Update: I will instead have this content ready for review by ~EOD tomorrow (5/15), not today (5/14)

**Comment by rwike77** [comment]
@aricrowe57  Thanks for the update.  Your text looks incomplete, though.  Thanks.

This could be an existing organization that 

Benefits

If you don't

**Comment by aricrowe57** [comment]
#sign-off

**Comment by aricrowe57** [comment]
@rwike77 , sorry, the content is complete now.  Would really appreciate if you're able to review and merge this.  Thank you!

**Comment by rwike77** [comment]
@aricrowe57  Thanks, looks good.  #sign-off

**Pull request merged**
