### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by MuhammadSufyan-humfoc**
This file has the details of Azure SSO integration.

### CODE REVIEW

**Comment by MuhammadSufyan-humfoc** [comment]
@microsoft-github-policy-service agree

**Comment by MuhammadSufyan-humfoc** [comment]
from where i can get ms.author  and etc ?

**Comment by Jak-MS** [comment]
@jeevansd @CelesteDG 
Can you review this new article? 

NOTE: since this PR introduces a new article, if it is approved, the commits will have to be moved to the private repo for a full review, including Acrolinx and staging. Can you move these commits to the private repo and sign off on that PR? [Here are the steps](https://review.learn.microsoft.com/en-us/help/contribute/contribute-how-to-manage-act-guidelines-public-pr?branch=main#pull-public-commits-to-the-private-repo-for-updates-staging-publication) for moving the commits. Let us know if you'd like the PR review team's assistance.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by MuhammadSufyan-humfoc** [comment]
I have updated the file content.
Can you guys provide me with some information regarding **"Invalid value for 'ms.author'"**
cc: @Jak-MS @jeevansd @CelesteDG @AArnott

**Comment by CelesteDG** [comment]
#please-close
Content for SaaS tutorials need to be done in our internal content repo, not public. 
@MuhammadSufyan-humfoc Please reach out to the team internally to get this set up through the internal repo. Thank you.

**Comment by MuhammadSufyan-humfoc** [comment]
@CelesteDG 
Could you tell me how to contact them and how I can publish my documentation?
Thanks
cc: @jackwilMS  @jeevansd  @AArnott

**Comment by MuhammadSufyan-humfoc** [comment]
Could You please provide the details how can I publish my documentation to MS learn ?
Thanks

**Comment by MuhammadSufyan-humfoc** [comment]
Hi,
Can you please guide me how I can publish my documentation to learn platform ?
Thanks

**Comment by MuhammadSufyan-humfoc** [comment]
Hi,
Could you please guide me how I can publish my documentation to Microsoft learn .
Thanks.

**Comment by MuhammadSufyan-humfoc** [comment]
How is Single Sign ON Microsoft Entra documentation published by other providers?
Examples:
https://learn.microsoft.com/en-us/entra/identity/saas-apps/ihasco-training-tutorial
https://learn.microsoft.com/en-us/entra/identity/saas-apps/highq-tutorial

cc: @jackwilMS @jeevansd @AArnott

**Pull request closed without merging**
