### PR TITLE
Update second-nature-ai-tutorial.md

### PR DESCRIPTION
**Pull request by OrSecondNature**

### CODE REVIEW

**Comment by Court72** [comment]
@jeevansd

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by bhavanabhavvs** [comment]
@OrSecondNature Thanks for the changes! Created a separate PR in our private repo for updating the sign-on url pattern in the tutorial. Please expect the changes to be live in 1-2 working days. Thanks!
#please-close

**Comment by Gicheha** [comment]
#please-close

**Comment by bhavanabhavvs** [comment]
@jeevansd These changes are live now in the tutorial. Please help us to close this PR as i am unable to close the issue here.

**Pull request closed without merging**
