### PR TITLE
Update concept-fido2-hardware-vendor.md to remove duplicate key

### PR DESCRIPTION
**Pull request by DevClate**
Removed 61250591-b2bc-4456-b719-0b17be90bb30 as it was a duplicate. All other fields matched too.

### CODE REVIEW

**Comment by DevClate** [comment]
Hi, I'm receiving error "403: User is not authorized to access this URL" for the instructions and documentation. 

This is the URL that gives me the error: https://review.learn.microsoft.com/.auth/login/aad/callback

**Comment by ShannonLeavitt** [comment]
@Justinha

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Justinha** [comment]
#sign-off

**Comment by Justinha** [comment]
@DevClate thanks for the correction and sorry for delay. to work around the merge conflict, I fixed this on my side. #please-close

**Comment by DevClate** [comment]
No problem @Justinha Glad I could help

**Pull request closed without merging**
