### PR TITLE
Update concept-learn-about-groups.md

### PR DESCRIPTION
**Pull request by azarboon**
This fact should be clearly stated. Actually, this is one of the questions in Azure certification exam. Currently, this information is dispersed in the doc and is misleading. 

"User Administrator and Global Administrator role owners can manage all Assigned groups' members."

### CODE REVIEW

**Comment by Court72** [comment]
@shlipsey3

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by shlipsey3** [comment]
Thanks! We're currently revisiting how we mention Global Administrator in documentation. I'm having a colleague take a look to make sure we're being consistent.

**Comment by MicrosoftGuyJFlo** [comment]
@shlipsey3 Correct, we should not mention Global Administrator in this context. At least Groups Administrator is correct as written in the linked article, but I would remove the other highly privileged roles talked about in the how to article. Let me know if you need any help removing those references.

**Comment by shlipsey3** [comment]
@azarboon - I'm going to set up a separate work item to tackle this work, as there are related articles that should get an update at the same time. We are moving away from mentioning Global Admin wherever possible, if there's a least privileged role available.
I'm going to close this PR (after giving chance to reply) and will try and tackle this week.

**Comment by shlipsey3** [comment]
Handling this request separately.

#please-close

**Pull request closed without merging**
