### PR TITLE
Update and rename whitesource-tutorial.md to mend.io-tutorial.md

### PR DESCRIPTION
**Pull request by lukebrogan-mend**
Updated documentation from Whitesource to Mend.io

### CODE REVIEW

**Comment by lukebrogan-mend** [comment]
@microsoft-github-policy-service agree [company="{Mend.io}"]

<https://www.mend.io/>
Luke Brogan
Sales Engineering Team Lead, EMEA & APAC
P. -44-750-8736205
Oxford
United Kingdom
www.mend.io
[image: Linkedin] <https://www.linkedin.com/company/mend-io> [image:
Twitter] <https://twitter.com/mend_io> [image: Facebook]
<https://www.facebook.com/mendappsec> [image: YouTube]
***@***.***_io>

**Comment by lukebrogan-mend** [comment]
@microsoft-github-policy-service agree company="Mend.io"
<https://www.mend.io/>
Luke Brogan
Sales Engineering Team Lead, EMEA & APAC
P. -44-750-8736205
Oxford
United Kingdom
www.mend.io
[image: Linkedin] <https://www.linkedin.com/company/mend-io> [image:
Twitter] <https://twitter.com/mend_io> [image: Facebook]
<https://www.facebook.com/mendappsec> [image: YouTube]
***@***.***_io>

**Comment by Court72** [comment]
@jeevansd

Can you review the proposed changes? Note that the [validation warnings](https://github.com/MicrosoftDocs/entra-docs/pull/1003#issuecomment-2228738387) must be resolved before merging.
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by bhavanabhavvs** [comment]
@lukebrogan-mend Thanks for the changes! Creating separate PR for your suggested changes in our private repo for better content validation and the change will be done in 1-2 days. Thanks!
#please-close

**Pull request closed without merging**
