### PR TITLE
Update troubleshoot-sspr-writeback with more details

### PR DESCRIPTION
**Pull request by tajaber**
Update troubleshoot-sspr-writeback.md file with detailed steps and one image

### CODE REVIEW

**Comment by Jak-MS** [comment]
@Justinha 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Justinha** [comment]
#sign-off

**Comment by Court72** [comment]
@justinha,

The following issues must be resolved before merging:

docs/identity/authentication/media/troubleshoot-sspr-writeback/heartbeat-eventvwr-log.png

- Any personal information must be obscured by using an opaque color block the same color as the background or by replacing the personal information with fictitious information (blurring isn't allowed).
- Consider changing the new file name to "heartbeat-event-viewer-log.png" to avoid unnecessary abbreviations.

docs/identity/authentication/troubleshoot-sspr-writeback.md

- Line 62: Revise the new alt text so that it describes the media type (for example, "Screenshot of...") and ends with a period.

This PR adds new content that needs to be moved to the private repo for staging and other checks.
Can you move the commits? Let us know if you'd like the PR review team's help.

Thanks
#hold-off

**Comment by Justinha** [comment]
@Court72 attached is an updated and renamed image. Can you add it on your side and revise al text to say "Screenshot of Event ID 31019 in the Application log of Event Viewer."

heartbeat-event-viewer-log

**Comment by Justinha** [comment]
#sign-off

**Comment by Court72** [comment]
@Justinha - Can you sign off in https://github.com/MicrosoftDocs/entra-docs-pr/pull/3015 where these commits have been moved?

Thanks!

**Pull request closed without merging**
