### PR TITLE
Update 4me-provisioning-tutorial.md: Remove DELETE limitation

### PR DESCRIPTION
**Pull request by matsimon**
According to 4Me's documentation they do support DELETE operations so no need to mention that as a limitation (anymore).

See:
* https://developer.4me.com/v1/scim/users/#delete-a-user
* https://developer.4me.com/v1/scim/groups/#delete-a-group

### CODE REVIEW

**Comment by American-Dipper** [comment]
@CelesteDG - can you review the proposed changes? Or tell use whom to direct this to? The author appears to not be available.  

 
IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.  

 

#label:"aq-pr-triaged" 

@MicrosoftDocs/public-repo-pr-review-team

**Comment by v-hgampala** [comment]
@twimmers, will you please confirm me the change so, we'll update the document as per the request?

**Comment by v-missam** [comment]
@matsimon @v-hgampala -   4me doesn’t support HARD DELETE of Users. SCIM users are never really deleted in 4me, instead the "active" attribute of the SCIM user will be set to "false " and the related 4me person's record will be disabled. This is specified in the link https://developer.4me.com/v1/scim/users/#delete-a-user .  So, we will update our tutorial with the above statement.

**Comment by Harshita-130901** [comment]
We created a separate PR for these changes in our private repo for better content validation. So, the changes will be live in 1 to 2 business days.
#please-close

**Comment by matsimon** [comment]
> @matsimon @v-hgampala - 4me doesn’t support HARD DELETE of Users. SCIM users are never really deleted in 4me, instead the "active" attribute of the SCIM user will be set to "false " and the related 4me person's record will be disabled. This is specified in the link https://developer.4me.com/v1/scim/users/#delete-a-user . So, we will update our tutorial with the above statement.

Thanks for highlighting that fine, yet important detail. When I was debugging a stalled SCIM sync at that moment, the current doc first lead me down the wrong track as it indicated a "doesn't support DELETE at all". Whereas it actually means "we do support DELETE, but actually won't actually delete users".

I'll welcome that update on the private branch whenever it hits the public docs :-)

**Pull request closed without merging**
