### PR TITLE
Update in-case-of-crisis-online-portal-tutorial.md

### PR DESCRIPTION
**Pull request by rdsgit**
Please update the content in this section.  Original instruction for which URL to provide was incorrect.

### CODE REVIEW

**Comment by Court72** [comment]
@jeevansd

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rdsgit** [comment]
#sign-off. Thanks Courtney

**Comment by rdsgit** [comment]
Am I not the assigned author?  Please advise.

**Comment by Court72** [comment]
Hi @rdsgit,

@jeevansd is the assigned author.

**Comment by rdsgit** [comment]
sign-off

**Comment by rdsgit** [comment]
@jeevansd , could you approve this merge request?  Thank you.

**Comment by v-hgampala** [comment]
@rdsgit, I was creating a separate for your changes in our private repo, the changes will live within 2-3 business days.
#please-close

**Pull request closed without merging**
