### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by De1gad0**
Updated verbiage including Beeline Enterprise support communication, added a new screenshot, and removed an old unused screenshot

### CODE REVIEW

**Comment by Jak-MS** [comment]
@jeevansd 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by v-hgampala** [comment]
@De1gad0, we created a separate PR for your changes in our private repo by following the fixed format of our documentation template with the suggested changes. The changes will live within 2-3 working days.
#please-close

**Comment by De1gad0** [comment]
Good afternoon @v-hgampala - it looks like some, but not all of our changes were carried over into the new PR you created. Are we able to re-open this PR, or do I need to open a new PR? Are you able to explain why all of our changes did not make it in the PR you created? Thank you

**Comment by De1gad0** [comment]
881_Change01_MDfile
881_Change01_Live

**Comment by De1gad0** [comment]
881_Change02_MDfile
881_Change02_Live

**Comment by v-hgampala** [comment]
@De1gad0, yes, I have reviewed the PR which you created but that article doesn't follow the format of our documentation template. The Azure certificates and URLs which should copied were added in app side configuration section but those steps we performed at Entra side right. So, I added them in a sequence of actions we performed.

**Pull request closed without merging**
