### PR TITLE
Update citi-program-tutorial.md

### PR DESCRIPTION
**Pull request by jfineout-citi**
Grammar and clarifying some instructions.

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@jeevansd

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by jfineout-citi** [comment]
Just checking for an update.

**Comment by jfineout-citi** [comment]
Hi @ShannonLeavitt Sorry, to bug you. I realize there might be delays since the holidays just passed, but what's the expected timeframe for an update?

**Comment by Court72** [comment]
@jeevansd,

Could you review this proposed update to your article and enter `#sign-off` in a comment if it's approved for merge?
Thanks!

**Comment by Harshita-130901** [comment]
we're creating a separate PR for your changes in our private repo, you may expect the updated doc within 2-3 working days.
#please-close

**Pull request closed without merging**
