### PR TITLE
Update dagster-cloud-tutorial.md

### PR DESCRIPTION
**Pull request by garethbrickman**
Added minor corrections and links to official Dagster documentation

(I'm a Dagster employee/maintainer of the [dagster OSS project](https://github.com/dagster-io/dagster))

### CODE REVIEW

**Comment by Jak-MS** [comment]
@jeevansd 
Can you review the proposed changes? 

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by garethbrickman** [comment]
@Jak-MS Is @jeevansd even active anymore? His profile doesn't have any activity since Apr 2023

**Comment by bhavanabhavvs** [comment]
@garethbrickman Creating a separate PR for your changes in our private repo for better content validation. The changes in the tutorial would be live in 1-2 days. #please-close

**Comment by garethbrickman** [comment]
@bhavanabhavvs @Jak-MS How do I make changes in your private repo?

**Comment by bhavanabhavvs** [comment]
> @bhavanabhavvs @Jak-MS How do I make changes in your private repo?

@garethbrickman No action is required from you. I have created a PR for your changes and it is merged now. You can see your changes in the [tutorial](https://learn.microsoft.com/entra/identity/saas-apps/dagster-cloud-tutorial) now.

**Pull request closed without merging**
