### PR TITLE
Update Beeline Tutorial - 20240610

### PR DESCRIPTION
**Pull request by De1gad0**
PLEASE REMOVE "media/beeline-tutorial/client-access-url.png" from base repo
Updating sections 'Configure Microsoft Entra SSO' and 'Configure Beeline Enterprise SSO'. 
Thank you!

### CODE REVIEW

**Comment by Court72** [comment]
@jeevansd

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by De1gad0** [comment]
Good morning @jeevansd 
Just wanted to check in with you on this. 
Would you be able to please remove the image "media/beeline-tutorial/client-access-url.png" from the base repo? We also updated the sections 'Configure Microsoft Entra SSO' and 'Configure Beeline Enterprise SSO' sections of the tutorial.
Thank you!

**Comment by dylanAtWork** [comment]
Hey @Court72, just quickly reviewing the repo history it looks like @jeevansd hasn't been active recently(?) and it's been a little over a month.
I don't know the process here but is there someone else who could review this PR if he's unavailable/busy?

**Comment by Court72** [comment]
@jeevansd, @CelesteDG 

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge.

**Comment by dylanAtWork** [comment]
@CelesteDG @jeevansd  any updates on this? Just passed 2 months with no review.

**Comment by dylanAtWork** [comment]
#sign-off

**Comment by De1gad0** [comment]
#sign-off

**Comment by De1gad0** [comment]
Good morning @Court72, @jeevansd and @CelesteDG
Tagging for visibility. Are we able to get a review on this please?
Thank you!

**Comment by Court72** [comment]
@dhivyagana (per @jeevansd's OOF message) - Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge.

**Comment by bhavanabhavvs** [comment]
@De1gad0 Creating a separate PR for your changes for better validation in our private repo. Please expect the changes in the tutorial to be live in 1-2 days #please-close

**Comment by De1gad0** [comment]
Thank you @bhavanabhavvs !

**Pull request closed without merging**
