### PR TITLE
"SecurityGroup" emits security groups and directory roles

### PR DESCRIPTION
**Pull request by juntakata**
If the app manifest is configured to issue groups claim with "groupMembershipClaims": "SecurityGroup", directory role information is also added to groups claim. This is explained here: [Understanding the Microsoft Entra app manifest - Microsoft identity platform | Microsoft Learn](https://learn.microsoft.com/en-us/entra/identity-platform/reference-app-manifest#groupmembershipclaims-attribute). This behavior is not properly documented across Entra docs.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@billmath @cilwerner 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by billmath** [comment]
#sign-off

**Comment by Court72** [comment]
Thanks, @billmath.

@cilwerner - Can you review the changes to the Identity Platform articles?

#hold-off

**Comment by cilwerner** [comment]
LGTM

#sign-off

**Pull request merged**
