### PR TITLE
Update secretserver-on-premises-tutorial.md

### PR DESCRIPTION
**Pull request by tylerezimmerman**
This doc calls out that this integration works only for on-prem Secret Server. That is inaccurate and this works for both on-prem and Cloud versions of Secret Server

### CODE REVIEW

**Comment by Court72** [comment]
@jeevansd

Can you review the proposed changes? Note that the validation warnings must be resolved before merging.

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by tylerezimmerman** [comment]
@Court72 @jeevansd can this be merged?

**Comment by bhavanabhavvs** [comment]
Hi @tylerezimmerman, Please submit an update request in our [portal](https://microsoft.sharepoint.com/teams/apponboarding/Apps/SitePages/apprequest.aspx) to remove (on-premises) from the application name in your gallery listing first then once the listing is renamed in entra, our team will update it in the tutorial as well. If you face any access related issues for submission, please reach out to [SaaS apps team](https://github.com/MicrosoftDocs/entra-docs/pull/SaaSApplicationIntegrations@service.microsoft.com) or [App workflow team](https://github.com/MicrosoftDocs/entra-docs/pull/idappworkflows@microsoft.com)

**Comment by bhavanabhavvs** [comment]
> Hi @tylerezimmerman, Please submit an update request in our [portal](https://microsoft.sharepoint.com/teams/apponboarding/Apps/SitePages/apprequest.aspx) to remove (on-premises) from the application name in your gallery listing first then once the listing is renamed in entra, our team will update it in the tutorial as well. If you face any access related issues for submission, please reach out to [SaaS apps team](https://github.com/MicrosoftDocs/entra-docs/pull/SaaSApplicationIntegrations@service.microsoft.com) or [App workflow team](https://github.com/MicrosoftDocs/entra-docs/pull/idappworkflows@microsoft.com)

Gentle reminder, Please see my comment above.
#please-close

**Pull request closed without merging**
