### PR TITLE
Update overview-what-is-global-secure-access.md

### PR DESCRIPTION
**Pull request by michaelmsonne**
As I hear and read, UDP support is here as GA (have it in my prod tenant)

### CODE REVIEW

**Comment by Court72** [comment]
@kenwith

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by kenwith** [comment]
@michaelmsonne thank you for the grammar catch and fix. On UDP support it is not yet available for all the features yet. In particular, Internet Access and web content filtering are not yet supported.

**Comment by michaelmsonne** [comment]
@kenwith no problem - and yes I read it's missing for that still - let's hope is there soon 👌

**Comment by kenwith** [comment]
Thank you for the catch! Sorry on the delay, this was added in another PR. 

#please-close

**Pull request closed without merging**
