### PR TITLE
Update index-desktop.yml

### PR DESCRIPTION
**Pull request by bgavrilMS**
UWP has been deprecated

I also recommend deleting the content, but I am not sure how to.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@Dickson-Mwendia 
Can you review the proposed changes? 

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Dickson-Mwendia** [comment]
Thank you so much @bgavrilMS for opening this. I'll take over the work to deprecate the content as well.

**Review by Dickson-Mwendia — APPROVED** [review]

**Comment by Dickson-Mwendia** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@Dickson-Mwendia @bgavrilMS - unfortunately we can't remove the TOC entry without removing the article that it's linking to... and adding a redirect to another article.... and that should be done in the private repo, `entra-docs-pr` . 

@Dickson-Mwendia - can you open a PR in the private repo to take care of this? Thanks. I'll close this one.

**Pull request closed without merging**
