### PR TITLE
Updating the text for OIDC Provisioning

### PR DESCRIPTION
**Pull request by andrekolodochka**
The text must have been changed since the last update to this doc:

image

### CODE REVIEW

**Comment by ttorble** [comment]
@owinoakelo 

Can you review the proposed changes?  

IMPORTANT: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge.  

To enable correct assignment of PRs, please update the `author` metadata with your GitHub alias in a new PR in the private repo. Thanks.

#label:"aq-pr-triaged" 
@MicrosoftDocs/public-repo-pr-review-team

**Comment by owinoakelo** [comment]
@ttorble , please assign to @ZollnerdMSFT  to review and approve

**Comment by ttorble** [comment]
#assign: @ZollnerdMSFT 

Thanks @owinoakelo and @ZollnerdMSFT

**Comment by ZollnerdMSFT** [comment]
#sign-off

**Pull request merged**
