### PR TITLE
Create seraphic-tutorial.md

### PR DESCRIPTION
**Pull request by MariaSeraphic**

### CODE REVIEW

**Comment by MariaSeraphic** [comment]
@microsoft-github-policy-service agree company="seraphic algorithms ltd"

**Comment by Court72** [comment]
@mariaseraphic, Thanks for your contribution. A member of the content team will review it.

**Comment by Court72** [comment]
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by v-hgampala** [comment]
@MariaSeraphic, Seraphic Security is not listed in the Microsoft Entra App Gallery, please submit a request in our [portal](https://microsoft.sharepoint.com/teams/apponboarding/Apps) first and then will create the document for it once it's deployed into app list.
image
please contact `SaaSApplicationIntegrations@service.microsoft.com` for any support.
#please-close

**Pull request closed without merging**
