### PR TITLE
Update secure-your-domain.md

### PR DESCRIPTION
**Pull request by jpitcairn**
PowerShell hardening command in existing documentation sets Kerberos hardening to Disabled. Updated command and added two additional bullets to show what command will change.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@Justinha - 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Jak-MS** [comment]
@CelesteDG - temporarily assign to you until @Justinha can be assigned - that option is currently nonfunctional

**Comment by CelesteDG** [comment]
#reassign:@justinha

**Comment by jpitcairn** [comment]
Closed and reopened this PR as it seemed like some tags werent applied to this that others have.

**Review by Justinha — APPROVED** [review]

**Comment by Justinha** [comment]
#sign-off

**Pull request merged**
