### PR TITLE
Update pendo-tutorial.md

### PR DESCRIPTION
**Pull request by solitaryr**
Changed support contact info and prefer the App Federation Url over XML file.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@jeevansd @CelesteDG - 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by CelesteDG** [comment]
Tagging @v-hgampala to review this public PR.

**Comment by Jak-MS** [comment]
testing

#assign: @Jak-MS

**Comment by v-hgampala** [comment]
@solitaryr, thanks for raising the pull request!
will you please raise an update request in our [portal](https://microsoft.sharepoint.com/teams/apponboarding/Apps) to update the info in the gallery app so, we'll update the document accordingly?
please contact (**SaaSApplicationIntegrations@service.microsoft.com**) if you have any queries and access issues.

**Comment by solitaryr** [comment]
Which option exactly am I choosing?  I don't see anything for "update documentation".  This is not an update to the application only doc tweaks.

**Comment by v-hgampala** [comment]
@solitaryr, yes, If the changes only related to the doc, I am creating a separate PR for these changes in our repo for better content validation, the changes will publish within 2-3 working days and closing this request for now.
#please-close

**Pull request closed without merging**
