### PR TITLE
Update GitHub EMU GHE.com tutorial to point to the correct app

### PR DESCRIPTION
**Pull request by isaacmbrown**
I am told that the app linked from this tutorial is not correct, and customers should use the standard GitHub EMU app for both GitHub.com and GHE.com.

It is useful to keep the guide because it includes the correct URL values for enterprises on GHE.com. I've updated references to the app name and copied the instructions for the installation section from https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/github-enterprise-managed-user-tutorial.md?plain=1.

**NOTE**: We need these updates merged before 29 October?

### CODE REVIEW

**Review by wowyzga — APPROVED** [review]
LGTM

**Comment by Jak-MS** [comment]
@isaacmbrown - we can move forward with this PR after you've agreed to the CLA. please follow the instructions here: https://github.com/MicrosoftDocs/entra-docs/pull/1200#issuecomment-2419869193

@MicrosoftDocs/public-repo-pr-review-team

**Comment by isaacmbrown** [comment]
@microsoft-github-policy-service agree company="GitHub"

**Comment by ShannonLeavitt** [comment]
@jeevansd

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by isaacmbrown** [comment]
@jeevansd 👋 I updated this PR with some additional changes to the provisioning guides (for [SAML](https://learn.microsoft.com/en-us/entra/identity/saas-apps/github-enterprise-managed-user-provisioning-tutorial) and [OIDC](https://learn.microsoft.com/en-us/entra/identity/saas-apps/github-enterprise-managed-user-oidc-provisioning-tutorial)).

* Added the correct tenant URL for GHE.com: it helps us to have this information in the Entra docs to avoid telling people to substitute values in the Entra guides we're linking.
* Updated the sections about the access token: the required scope recently changed to `scim:enterprise`. I think it's easiest just to link to the docs on GitHub Docs for creating the token, in case of any future changes.

**Comment by v-missam** [comment]
@isaacmbrown @jeevansd I am working on a separate PR to address these changes. Will let you know once the change is merged.

**Comment by v-missam** [comment]
The change is already merged using a separate PR [https://github.com/MicrosoftDocs/entra-docs-pr/pull/5603](https://github.com/MicrosoftDocs/entra-docs-pr/pull/5603)

**Comment by v-missam** [comment]
#please-close

**Pull request closed without merging**
