### PR TITLE
Updating support URLs for GitHub documentation

### PR DESCRIPTION
**Pull request by harricross**
Hey all,
Harry from the GitHub Premium Plus support team here.

Opening a PR to update our support documentation for Entra ID with a URL change.

Thanks!

Harry

### CODE REVIEW

**Comment by Court72** [comment]
@jeevansd

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by bhavanabhavvs** [comment]
@harricross Creating a separate PR in our private repo for this change in the tutorial. Please expect the latest support contact to be reflected in the tutorial in 1-2 days. Thanks #please-close

**Comment by harricross** [comment]
Hey,
Thank you for doing this for me. We do need the language versions updated too, can you please let me know if there is a specific process for this?

Thanks

Harry

**Comment by bhavanabhavvs** [comment]
@harricross In general, it may take about two weeks from the time the original EN-US article is updated to when the localized versions will appear. Sometimes it may be less if the English version is updated right before the Loc team picks up the deltas each week. 

If after two weeks it’s still not updated, please reach out to our team (SaaSApplicationIntegrations@service.microsoft.com) we’ll definitely escalate further.

**Pull request closed without merging**
