### PR TITLE
Update procaire-tutorial.md

### PR DESCRIPTION
**Pull request by vahedq**
We are using company name (Praisidio) as our product name, and to avoid confusion for our users, we would like to replace "Procaire" with "Praisidio".

thank you so much.

### CODE REVIEW

**Comment by vahedq** [comment]
@microsoft-github-policy-service agree company="Praisidio"

**Comment by ShannonLeavitt** [comment]
@jeevansd

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by bhavanabhavvs** [comment]
Hi @vahedq, Please submit an update request in our [portal](https://microsoft.sharepoint.com/teams/apponboarding/Apps/SitePages/apprequest.aspx) first to rename the application in your gallery listing first then our team will update the name in the tutorial as follows. If you face any access related issues for submission, please reach out to [SaaS apps team](SaaSApplicationIntegrations@service.microsoft.com) or [App workflow team] (idappworkflows@microsoft.com)

**Comment by bhavanabhavvs** [comment]
> Hi @vahedq, Please submit an update request in our [portal](https://microsoft.sharepoint.com/teams/apponboarding/Apps/SitePages/apprequest.aspx) first to rename the application in your gallery listing then once the listing is renamed, our team will update the name in the tutorial as follows. If you face any access related issues for submission, please reach out to [SaaS apps team](SaaSApplicationIntegrations@service.microsoft.com) or [App workflow team](idappworkflows@microsoft.com)

Please see my above comment.

#please-close

**Pull request closed without merging**
