### PR TITLE
Update groups-dynamic-rule-more-efficient.md

### PR DESCRIPTION
**Pull request by yuhko-msft**
update des for "Minimize use of CONTAINS" section

### CODE REVIEW

**Comment by Jak-MS** [comment]
@barclayn 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by yuhko-msft** [comment]
quick follow up on this - can anyone help approve?


Thanks,

Ko



________________________________

**Comment by yuhko-msft** [comment]
@barclayn - can you help review?

**Review by barclayn — APPROVED** [review]

**Comment by barclayn** [comment]
#sign-off

**Comment by yuhko-msft** [comment]
adding @Kristina ***@***.***> for visibility!

doc change for "Minimize use of CONTAINS" is merged! we should see the change soon:)


Thanks,

Ko



________________________________

**Pull request merged**
