### PR TITLE
Update in-case-of-crisis-mobile-tutorial.md

### PR DESCRIPTION
**Pull request by rdsgit**
Changed Raw Certificate to Base64 Certificate

### CODE REVIEW

**Comment by rdsgit** [comment]
#sign-off

**Comment by rdsgit** [comment]
Am I not the assigned author? Please advise.

**Comment by Court72** [comment]
Hi @rdsgit,

@jeevansd is the assigned author.

**Comment by rdsgit** [comment]
sign-off

**Comment by rdsgit** [comment]
@jeevansd , could you approve this merge request?  Thank you.

**Comment by rdsgit** [comment]
How do I get this review processed?  Please advise if I'm missing a step here.  This is taking too long to approve.  Thank you.

**Comment by v-hgampala** [comment]
@rdsgit, we're creating a separate PR for this in our private repo for better content review, the changes will merge within 2-3 working days.
#please-close

**Pull request closed without merging**
