### PR TITLE
Delete docs/identity/saas-apps/secure-deliver-provisioning-tutorial.md

### PR DESCRIPTION
**Pull request by atsuko-ito**
We are requesting this file delete because currently does not offer this option.

### CODE REVIEW

**Comment by atsuko-ito** [comment]
@microsoft-github-policy-service agree company="FUJIFILM Software Co., Ltd."

**Comment by Court72** [comment]
@twimmers

Can you review the proposed changes? 

If you approve, a redirect for the deleted article must be added to the redirection file. These commits must also be moved into the private repo for staging and automated checks.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by billmath** [comment]
Checking with engineering.

**Comment by kenwith** [comment]
@atsuko-ito - please email me so we can discuss the request. My email is the same as my github and at microsoft.

**Comment by atsuko-ito** [comment]
@kenwith 
I sent you an email. Please reply if you haven't received it.

**Comment by v-hgampala** [comment]
@twimmers, please confirm, can we remove this article from the list?
if yes, I'll create separate PR in our repo for this.

**Comment by v-hgampala** [comment]
#please-close

**Pull request closed without merging**
