### PR TITLE
Update msal-android-shared-devices.md

### PR DESCRIPTION
**Pull request by aaglick**
Removing preview tags from M365 and outlook for Android apps.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@henrymbuguakiarie 
Can you review the proposed changes? 

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by Dickson-Mwendia — APPROVED** [review]

**Comment by Dickson-Mwendia** [comment]
Thank you so much @aaglick for the update. Looks good

#sign-off

**Comment by Dickson-Mwendia** [comment]
@henrymbuguakiarie could you please help sign off this PR?

**Review by henrymbuguakiarie — APPROVED** [review]
LGTM

**Comment by henrymbuguakiarie** [comment]
#sign-off

**Pull request merged**
