### PR TITLE
Steps were in the wrong order

### PR DESCRIPTION
**Pull request by jessehouwing**
- Made the naming of GitHub Organization consistent (github app, github team etc)
- Removed the text referencing to add a new github app in case one didn't exist before. You can't do that without first completely configuring SAML as mentioned in the prerequisites.

### CODE REVIEW

**Comment by jessehouwing** [comment]
The document is missing an important element:


>  To use SCIM with your organization, you must use a third-party-owned OAuth app. The OAuth app must be authorized by, and subsequently acts on behalf of, a specific GitHub user. If the user who last authorized this OAuth app leaves or is removed from the organization, SCIM will stop working. To avoid this issue, we recommend creating a dedicated user account to configure SCIM. This user account must be an organization owner and will consume a license.

This is mentioned in the Okta docs over in GitHub, but is missing from the EntraID docs. Since the integration relies on a similar OAuth app, the same guidance should be provided.

**Comment by Court72** [comment]
@twimmers

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by v-hgampala** [comment]
@v-missam, can you please review the proposed changes in PR?

**Comment by v-missam** [comment]
#sign-off

**Comment by v-hgampala** [comment]
@jessehouwing, we have created separate PR for your changes in our private repo for better content validation- https://github.com/MicrosoftDocs/entra-docs-pr/pull/2076
#please-close

**Pull request closed without merging**
