### PR TITLE
Updating PureStorage tutorial for updating role values

### PR DESCRIPTION
**Pull request by skeerthivasan**

### CODE REVIEW

**Comment by Jak-MS** [comment]
@jeevansd 
Can you review the proposed changes? 

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by skeerthivasan** [comment]
@jeevansd , can you please check this and approve ?

**Comment by Court72** [comment]
@dhivyagana (per @jeevansd's OOF message) - Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge.

**Comment by bhavanabhavvs** [comment]
@skeerthivasan Creating a separate PR for better content validation in our private repo for your changes to merge it in the tutorial. Please expect your changes to be live in 1-2 days. #please-close

**Comment by skeerthivasan** [comment]
> @skeerthivasan Creating a separate PR for better content validation in our private repo for your changes to merge it in the tutorial. Please expect your changes to be live in 1-2 days. #please-close

@bhavanabhavvs , Thanks. I need add below content as well, please adapt the same.

In Configure Microsoft Entra SSO, for line item 8, add these in notes or any form of highlighting text.

Edit default roles in the Entra app and update their values as "storage_admin", "ops_admin", "readonly", "array_admin" respectively.
The links below should help you to do the same.
Refer "App roles UI - section for updating values" - https://learn.microsoft.com/en-us/entra/identity-platform/howto-add-app-roles-in-apps#app-roles-ui
Refer "Assign users and groups to Microsoft Entra roles - section for role assignment" - https://learn.microsoft.com/en-us/entra/identity-platform/howto-add-app-roles-in-apps#app-roles-ui

In Configure Pure Storage SSO, for line item 3, add this instruction as well.

Get verification certificate from Entra app and update in FlashArray SSO Configuration for "Verification Certificate" field.
You can follow the steps shown in the document below to get a relevant certificate.

https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/tutorial-manage-certificates-for-federated-single-sign-on

**Comment by bhavanabhavvs** [comment]
Sure @skeerthivasan , I will add it. Thanks for the heads up!

**Pull request closed without merging**
