### PR TITLE
Update lusid-provisioning-tutorial.md

### PR DESCRIPTION
**Pull request by MVBond**
Use aadOptscim062020 flag detailed [here](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/application-provisioning-config-problem-scim-compatibility#flags-to-alter-the-scim-behavior). LUSID only supports group PATCHing as described in the SCIM RFCs

### CODE REVIEW

**Comment by Jak-MS** [comment]
@twimmers 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by MVBond** [comment]
@Jak-MS it's been 3 weeks, is there anyone else who can review?

**Comment by Court72** [comment]
@twimmers, @jeevansd 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.

**Comment by v-missam** [comment]
@Court72 @Jak-MS @MVBond 

- aadOptscim062020 flag is appended to tenant URL of non-gallery application(only) in order to change the default SCIM client behavior to expected SCIM client behavior, while testing or setting up your SCIM endpoint.
- But it is not required in a gallery app, as they already support expected SCIM client behavior.

Hope we are clear.

**Comment by v-missam** [comment]
#please-close

**Comment by MVBond** [comment]
@v-missam thanks for the clarification

**Pull request closed without merging**
