### PR TITLE
Update promaster-tutorial.md

### PR DESCRIPTION
**Pull request by Chadinlogik**
Requested by management to remove all mention of CUSTOM DOMAINS because they're not relevant to our new, rebranded product.

### CODE REVIEW

**Comment by Chadinlogik** [comment]
Hello all
I'd just like to confirm that the update is still pending a review, is this correct?
Regards
Chad

**Comment by Court72** [comment]
Hi @chadinlogik, that's correct.

@jeevansd - Can you review the proposed changes to your article?

**Comment by v-hgampala** [comment]
@Chadinlogik, we're creating a separate PR for this request in our private repo to avoid content validation errors, the changes will merge within 2-3 working days.
#please-close

**Comment by Chadinlogik** [comment]
Hi All
Just checking in on the below. Should I create a new request?
Regards
Chad

**Comment by v-hgampala** [comment]
@Chadinlogik, It was already updated as per the request, please check the article again and let us know-
image

**Pull request closed without merging**
