### PR TITLE
Integration tutorial updated

### PR DESCRIPTION
**Pull request by Khashrul**
Updated the  integration tutorial.

### CODE REVIEW

**Comment by Khashrul** [comment]
@microsoft-github-policy-service agree company="Othership"

**Comment by Court72** [comment]
@Khashrul  - Thank you for your contribution. It looks like the system didn't recognize your initial CLA signature. Would you take a moment to sign the Contributor License Agreement (CLA) again? After the CLA is accepted, someone can review your pull request. Thanks!

**Comment by Khashrul** [comment]
> @Khashrul - Thank you for your contribution. It looks like the system didn't recognize your initial CLA signature. Would you take a moment to sign the Contributor License Agreement (CLA) again? After the CLA is accepted, someone can review your pull request. Thanks!

Can you please help me how i sign the Contributor License Agreement (CLA) ?

**Comment by Court72** [comment]
> Can you please help me how i sign the Contributor License Agreement (CLA) ?

@Khashrul - The signature was successful. Thanks!

**Comment by Court72** [comment]
@jeevansd

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.

**Comment by Harshita-130901** [comment]
we're creating a separate PR for the changes in our private repo, you may expect the updated doc within 2-3 working days.
#please-close

**Pull request closed without merging**
