### PR TITLE
Add code markers around powershell cmdlets and fix some of them

### PR DESCRIPTION
**Pull request by cnotin**
* Backticks were missing
* Some commands used long dash (used for english text) instead of normal '-' dash

### CODE REVIEW

**Comment by American-Dipper** [comment]
@billmath - can you review the proposed changes?  For some reason (is this a new repo?) I'm unable to assign this PR to you.

 
IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.  

 

#label:"aq-pr-triaged" 

@MicrosoftDocs/public-repo-pr-review-team

**Comment by CelesteDG** [comment]
Thank you, @American-Dipper - The access issues should be addressed now. 
Assigned this to @billmath

**Comment by American-Dipper** [comment]
[like]  Jeff Borsecnik (AQUENT LLC) reacted to your message:
________________________________

**Comment by billmath** [comment]
#sign-off

**Pull request merged**
