### PR TITLE
Update onyxia-tutorial.md

### PR DESCRIPTION
**Pull request by Daniellamm**
Only copy the SSO URL and not all the URLs

### CODE REVIEW

**Comment by Jak-MS** [comment]
@jeevansd 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by v-hgampala** [comment]
@Daniellamm, In the documentation, we haven't mentioned about the SSO URL field or any Onyxia SSO configuration steps, we suggested to contact application support team to get it configured, then how we could suggest only copying Login URL, even though that is the only required filed from Azure?

**Comment by Daniellamm** [comment]
@v-hgampala  I am from the Onyxia team and I am testing the edit process before we make more edits to fully customize the instructions to match what is on the Onyxia platform

**Comment by v-hgampala** [comment]
@Daniellamm, at the time we are creating the document, we didn't have app credentials to add the configuration steps, please provide the Onyxia test account with admin rights so we can modify the tutorial much better with configuration steps.
please share credentials to my id - v-hgampala@microsoft.com

**Comment by Daniellamm** [comment]
@v-hgampala I just sent you the email. Let me know if you have any questions. Thanks

**Comment by v-hgampala** [comment]
#please-close

**Pull request closed without merging**
