### PR TITLE
Update licensing-ps-examples.md

### PR DESCRIPTION
**Pull request by SteveMutungi254**
Update Licensing PowerShell Examples with Microsoft Graph PowerShell equivalents.

### CODE REVIEW

**Comment by v-emilypr** [comment]
#sign-off

**Comment by v-emilypr** [comment]
Hi @barclayn, @SteveMutungi254 has finalized work on this PR. GH requires your sign off for review and merge. Appreciate your assistance!

**Review by barclayn — CHANGES_REQUESTED** [review]
Steve, this looks fine except for the metadata. The older version or the article has the correct metadata that needs to be preserved.  You can remove the 'keywords:' section

**Review by omondiatieno — APPROVED** [review]
LGTM!

**Comment by omondiatieno** [comment]
#sign-off

**Comment by omondiatieno** [comment]
reassign:omondiatieno

**Comment by barclayn** [comment]
#sign-off

**Pull request merged**
