### PR TITLE
Update businessmap-tutorial.md

### PR DESCRIPTION
**Pull request by mihail-knbz**
URLs for Businessmap accounts are https://subdomain.kanbanize.com

### CODE REVIEW

**Comment by Court72** [comment]
@jeevansd

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by mihail-knbz** [comment]
@jeevansd #sign-off Can you please review and approve the text changes?

**Comment by mihail-knbz** [comment]
@jeevansd @Court72 Can someone look into this please? It has been opened more than a month ago and it still hasn't been processed. We are having clients complain about the incorrect information in the article.

**Comment by Court72** [comment]
I sent a Teams message to @jeevansd today.

**Comment by jeevansd** [comment]
#sign-off

**Pull request merged**
