### PR TITLE
Update faqs.md to remove GA requirements

### PR DESCRIPTION
**Pull request by mrudulahg01**

### CODE REVIEW

**Comment by Court72** [comment]
@jenniferf-skc

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by jenniferf-skc — APPROVED** [review]

**Comment by jenniferf-skc** [comment]
#sign-off

**Review by jenniferf-skc — APPROVED** [review]

**Comment by jenniferf-skc** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@mrudulahg01 - can you mark this PR "Ready for review" when you're ready for the changes to go live?  Thanks.

**Comment by jenniferf-skc** [comment]
#ready-for-review

**Comment by jenniferf-skc** [comment]
Hi @Jak-MS I don't see where to select Ready for Review at the bottom of the PR. This can be reviewed and merged.

**Comment by Court72** [comment]
@mrudulahg01, @jenniferf-skc - I resolved the merge conflicts in this PR and there are no remaining changes. The [live article](https://learn.microsoft.com/entra/permissions-management/faqs#how-is-permissions-management-being-deployed) has been updated.

**Pull request closed without merging**
