### PR TITLE
Update confluencemicrosoft-tutorial.md

### PR DESCRIPTION
**Pull request by v-ymundhe**
document file updated

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@dhivyagana - Can you review the proposed changes? Note that before we can merge, the exposed GUIDs must be removed from the image, and the image file name must be changed to all lowercase.

IMPORTANT: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by dhivyagana** [comment]
#sign-off

**Review by dhivyagana — APPROVED** [review]
#sign-off

**Comment by dhivyagana** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@v-ymundhe @dhivyagana  - 

1. we can't use github links to images. i've changed the link to `./media/confluencemicrosoft-tutorial/sso-plugin-configuration-page.png` which should work **after** the image file name is changed to match our criteria. (no uppercase characters allowed). 

1. In addition, the image itself contains private information that must be removed or obscured (by masking it with the background color - no colored blocks or blurring) ... Every time there is all or part of the Entity ID ... it must be masked or replaced with *obviously* false fake ID.

   image

1. The Certificate data must also be obscured.

After you've made these changes, tag @dhivyagana to review and sign-off and I will take another look. Thanks.

#hold-off

**Comment by v-ymundhe** [comment]
Hi @Jak-MS @dhivyagana 
I have replaced image file and also file is visible in doc. Please check and let me know if any.

**Comment by Jak-MS** [comment]
thanks @v-ymundhe - looks great!

@dhivyagana - merging this based on your previous approval. nothing has changed except to pass pr review. thanks!

**Pull request merged**
