### PR TITLE
KloudIdentity SCIM gateway added to partner driven integrations.

### PR DESCRIPTION
**Pull request by AselaSamarakoon**
KloudIdentity SCIM gateway added under the partner driven integrations.

### CODE REVIEW

**Comment by AselaSamarakoon** [comment]
@microsoft-github-policy-service agree company="Kloudynet Technologies Sdn Bhd"

________________________________

**Comment by Jak-MS** [comment]
@billmath 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ArvindHarinder1** [comment]
#sign-off

**Comment by billmath** [comment]
#sign-off

**Pull request merged**
