### PR TITLE
Update troubleshoot-saml-based-sso.md

### PR DESCRIPTION
**Pull request by jsoveral**
Adding a note on why the scenario where UX disables the add identifier.

### CODE REVIEW

**Comment by Court72** [comment]
@omondiatieno

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by omondiatieno — APPROVED** [review]
@jsoveral I'll sign off after you've committed the minor suggestion. Thank you.

**Comment by jsoveral** [comment]
@omondiatieno I have created a commit with your proposed changes.

**Comment by omondiatieno** [comment]
#sign-off

**Comment by omondiatieno** [comment]
#sign-off

**Pull request merged**
